### PR TITLE
feat: add openrazer-daemon-only package

### PR DESCRIPTION
**Pull request by dreamyukii**
this pr will add openrazer-daemon without depends on openrazer-kmod, useful for building systemd-sysext package since it doesn't pull openrazer-kmod package which is important for systemd system extensions.

### CODE REVIEW

**Comment by my4ng** [comment]
I have streamlined the package creation in fedora-my4ng, I am going to migrate those here and have it as a submodule there. 

As for this PR, I'd like to investigate what happens with the kernel module, and maybe change the requires to recommends. @dreamyukii Would that work as an extension?

**Comment by dreamyukii** [comment]
> I have streamlined the package creation in fedora-my4ng, I am going to migrate those here and have it as a submodule there.
> 
> As for this PR, I'd like to investigate what happens with the kernel module, and maybe change the requires to recommends. @dreamyukii Would that work as an extension?

i think yes, system extension only need the daemon for reducing package size

**Comment by dreamyukii** [comment]
i think this is good? @my4ng

**Comment by my4ng** [comment]
I don't think it's feasible to migrate from my repo, one of the reasons being that they are of the main branch rather than release. For this one I think the best is to just make it recommend.

**Pull request merged**
